dist: trusty
sudo: false
language: php
php:
  - 5.6
  - 7.0
  - hhvm

before_install:
  - nvm install 6.0.0
  - npm install -g yarn
matrix:
  allow_failures:
    - php: hhvm

cache:
  yarn: true
  directories:
  - vendor

before_script:
  - composer install -o
  - yarn install
  - if [ `php-config --vernum` -ge 70000 ] ; then export USE_STRICT_TYPES=true ; fi
script:
  - npm test

after_script:
  - npm run test-server-close
