language: node_js
php:
  - 5.6
  - 7.0
  - hhvm
node_js:
  - "node"
matrix:
  allow_failures:
    - php: hhvm

cache:
  directories:
  - vendor
  - node_modules

before_script:
  - composer install -o
  - npm install
  - if [ `php-config --vernum` -ge 70000 ] ; then export USE_STRICT_TYPES=true ; fi
script:
  - npm run test:unit
