language: php
php:
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - composer install -o
  - npm install
  - if [ `php-config --vernum` -ge 70000 ] ; export USE_STRICT_TYPES=true ; fi
script:
  - npm run test
